# Generated by Django 5.2.12 on 2026-03-13 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_sessions', to='configs.configversion')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_sessions', to='studies.study')),
            ],
        ),
    ]
