# Generated by Copilot on 2026-05-14

from django.db import migrations, models


def backfill_run_variant_fields(apps, schema_editor):
    RunSession = apps.get_model('runs', 'RunSession')
    AuditEvent = apps.get_model('audit', 'AuditEvent')

    run_ids = list(
        RunSession.objects.exclude(id__isnull=True).values_list('id', flat=True)
    )
    if not run_ids:
        return

    events = AuditEvent.objects.filter(
        action='start_run',
        resource_type='run_session',
        resource_id__in=[str(run_id) for run_id in run_ids],
    ).order_by('-created_at')

    variant_by_run_id = {}
    for event in events:
        run_id = str(getattr(event, 'resource_id', '') or '').strip()
        if not run_id or run_id in variant_by_run_id:
            continue
        metadata = event.metadata_json if isinstance(getattr(event, 'metadata_json', None), dict) else {}
        variant_id = str(metadata.get('flow_variant_id') or '').strip()
        variant_label = str(metadata.get('flow_variant_label') or '').strip()
        if variant_id or variant_label:
            variant_by_run_id[run_id] = (
                variant_id,
                variant_label or variant_id,
                True,
            )

    for run in RunSession.objects.all():
        key = str(run.id)
        if key not in variant_by_run_id:
            continue
        variant_id, variant_label, has_variant = variant_by_run_id[key]
        updated = False
        if run.flow_variant_id != variant_id:
            run.flow_variant_id = variant_id
            updated = True
        if run.flow_variant_label != variant_label:
            run.flow_variant_label = variant_label
            updated = True
        if run.has_flow_variant != has_variant:
            run.has_flow_variant = has_variant
            updated = True
        if updated:
            run.save(update_fields=['flow_variant_id', 'flow_variant_label', 'has_flow_variant'])


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_runsession_owner_user'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsession',
            name='flow_variant_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='runsession',
            name='flow_variant_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='runsession',
            name='has_flow_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_run_variant_fields, migrations.RunPython.noop),
    ]
