# Generated by Django 5.2.12 on 2026-03-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
        ("runs", "0001_initial"),
        ("users", "0002_userprofile_mfa_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE studies_study "
                "ADD COLUMN IF NOT EXISTS owner_user_id bigint NULL "
                "REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;"
            ),
            reverse_sql=(
                "ALTER TABLE studies_study "
                "DROP COLUMN IF EXISTS owner_user_id;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS studies_study_owner_user_id_idx "
                "ON studies_study(owner_user_id);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS studies_study_owner_user_id_idx;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE runs_runsession "
                "ADD COLUMN IF NOT EXISTS owner_user_id bigint NULL "
                "REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;"
            ),
            reverse_sql=(
                "ALTER TABLE runs_runsession "
                "DROP COLUMN IF EXISTS owner_user_id;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS runs_runsession_owner_user_id_idx "
                "ON runs_runsession(owner_user_id);"
            ),
            reverse_sql=(
                "DROP INDEX IF EXISTS runs_runsession_owner_user_id_idx;"
            ),
        ),
    ]
