# Generated by Django 5.2.12 on 2026-04-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_study_researcher_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('researcher', 'Researcher'), ('analyst', 'Analyst'), ('participant', 'Participant')], default='researcher', max_length=50),
        ),
    ]
