# Generated by Django 5.2.12 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="public_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
