# Generated by Django 5.2.16 on 2026-08-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('researcher', 'Researcher'), ('instructor', 'Instructor'), ('student', 'Student'), ('analyst', 'Analyst'), ('participant', 'Participant')], default='researcher', max_length=50),
        ),
    ]
