# Generated by Django 5.2.12 on 2026-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='system', max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=128)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
