# Generated by Django 5.2.16 on 2026-08-02 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_study_launch_properties_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('section_name', models.CharField(max_length=120)),
                ('enrollment_code_digest', models.CharField(max_length=64, unique=True)),
                ('enrollment_code_hint', models.CharField(blank=True, default='', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructed_course_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course_name', 'section_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('teaching_assistant', 'Teaching Assistant'), ('student', 'Student')], max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='studies.coursesection')),
            ],
            options={
                'ordering': ['course_section_id', 'role', 'user_id'],
            },
        ),
        migrations.AddField(
            model_name='study',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='studies.coursesection'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('instructor_user', 'course_name', 'section_name'), name='uniq_instructor_course_section'),
        ),
        migrations.AddConstraint(
            model_name='coursemembership',
            constraint=models.UniqueConstraint(fields=('course_section', 'user'), name='uniq_course_section_user'),
        ),
    ]
